### ISSUE TITLE
El código no funciona

### ISSUE THREAD

**Issue by georgeemr** [interactuamovil/im-contactosms-sdk-dotnet#4]

**Comment by sergeiw** [comment]
Gracias George por tu reporte.  Podrías dar más detalle sobre las pruebas que hiciste e indicar los pasos para poder reproducirlo.  Gracias

**Comment by georgeemr** [comment]
Hola que tal, con todo el gusto.
Recientemente adquirimos el api para enviar los sms por medio de una URL.
Hoy descubrí este proyecto en la dirección de ayuda https://notificame.claro.cr/help.

Usando el proyecto ApiExample-3.5 procedí a colocar el KEY, la URL y el MSISDN y seguidamente llamo el metodo SendMessageToContact(msisdn);

`string url = "https://notificame.claro.cr/http/"; /* ej: http://<url>/api/ */`

El código da Object reference not set to an instance of an object.

La URL utilizada es la de Costa Rica. y el error básicamente es porque no puede parsear el dataResponse porque esta retornando vacio.

**Comment by sergeiw** [comment]
Gracias George. Este SDK es para el API REST y estas usando el URL del API HTTP.  Te comparto el URL correcto para tu configuración:
https://notificame.claro.cr/api/rest/

**Comment by georgeemr** [comment]
De maravilla, ahora si me retorna respuesta. Pero me indica no autorizado. Veo que hay una variable que se llama 'secret' pero no tengo el dato. Debo solicitarlo con el encargado aquí en mi país?

**Comment by sergeiw** [comment]
Si asi es. Gracias por tomarte el tiempo de reportar y esperamos que puedas realizar tu desarrollo sin más contratiempos.

**Comment by georgeemr** [comment]
Gracias a usted!
